/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-06-24 13:12:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet/scss\" type=\"text/css\" href=\"test.scss\">\r\n");
      out.write("<link rel=\"icon\" href=\"Images/icon4.ico\" />\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tfont-family: -apple-system, BlinkMacSystemFont, \"San Francisco\",\r\n");
      out.write("\t\tHelvetica, Arial, sans-serif;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html, body {\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\twidth: 100vw;\r\n");
      out.write("\tmargin: 0 0;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: flex-start;\r\n");
      out.write("\tjustify-content: flex-start;\r\n");
      out.write("\tbackground: #f3f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("\tfont-size: 24px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\topacity: 0.85;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tfont-size: 12.5px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form {\r\n");
      out.write("\tpadding: 40px 30px;\r\n");
      out.write("\tbackground: #fefefe;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\talign-items: flex-start;\r\n");
      out.write("\tpadding-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form h4 {\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .5);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form h4 span {\r\n");
      out.write("\tcolor: rgba(0, 0, 0, 1);\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form p {\r\n");
      out.write("\tline-height: 155%;\r\n");
      out.write("\tmargin-bottom: 5px;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\topacity: 0.65;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\tmax-width: 200px;\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.discrete {\r\n");
      out.write("\tcolor: rgba(0, 0, 0, .4);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tborder-bottom: solid 1px rgba(0, 0, 0, .0);\r\n");
      out.write("\tpadding-bottom: 4px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tfont-weight: 300;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.discrete:hover {\r\n");
      out.write("\tborder-bottom: solid 1px rgba(0, 0, 0, .2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tmin-width: 100px;\r\n");
      out.write("\tborder-radius: 24px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding: 15px 40px;\r\n");
      out.write("\tmargin-top: 5px;\r\n");
      out.write("\tbackground-color: #148de0;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tfont-weight: 500;\r\n");
      out.write("\tbox-shadow: 0px 2px 6px -1px rgba(0, 0, 0, .13);\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("\ttransform: translateY(-3px);\r\n");
      out.write("\tbox-shadow: 0 2px 6px -1px rgba(182, 157, 230, .65);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover:active {\r\n");
      out.write("\ttransform: scale(0.99);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tpadding: 20px 0px;\r\n");
      out.write("\theight: 56px;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tborder-bottom: solid 1px rgba(0, 0, 0, .1);\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tmin-width: 280px;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("\ttransition: all 0.3s linear;\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: 400;\r\n");
      out.write("\t-webkit-appearance: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input:focus {\r\n");
      out.write("\tborder-bottom: solid 1px #b69de6;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tbox-shadow: 0 2px 6px -8px rgba(182, 157, 230, .45);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".floating-label {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".floating-label label {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: calc(50% - 7px);\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\topacity: 0;\r\n");
      out.write("\ttransition: all 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".floating-label\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("input\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(":not\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("(\r\n");
      out.write(":placeholder-shown\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(")\r\n");
      out.write("{\r\n");
      out.write("padding\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(":\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("28\r\n");
      out.write("px\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("0\r\n");
      out.write("px\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("12\r\n");
      out.write("px\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("0\r\n");
      out.write("px\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(";\r\n");
      out.write("}\r\n");
      out.write(".floating-label input:not (:placeholder-shown ) +label {\r\n");
      out.write("\ttransform: translateY(-10px);\r\n");
      out.write("\topacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".session {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin: auto auto;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tbox-shadow: 0px 2px 6px -1px rgba(0, 0, 0, .12);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left {\r\n");
      out.write("\twidth: 220px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmin-height: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tbackground-image: url(\"Images/login.jpg\");\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tborder-top-left-radius: 4px;\r\n");
      out.write("\tborder-bottom-left-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left svg {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tmargin: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"session\">\r\n");
      out.write("\t\t<div class=\"left\"></div>\r\n");
      out.write("\t\t<form action=\"login\" class=\"log-in\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("\t\t\t<h4>\r\n");
      out.write("\t\t\t\tNous sommes <span>LUXE</span>\r\n");
      out.write("\t\t\t</h4>\r\n");
      out.write("\t\t\t<p>Bienvenue à nouveau ! Connectez-vous maintenant pour gérer votre agence :</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"floating-label\">\r\n");
      out.write("\t\t\t\t<input placeholder=\"Username\" type=\"text\" name=\"username\" id=\"username\" autocomplete=\"off\"> <label for=\"email\">Username:</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"floating-label\">\r\n");
      out.write("\t\t\t\t<input placeholder=\"Password\" type=\"password\" name=\"password\" id=\"password\" autocomplete=\"off\" class=\"\"> <label for=\"password\">Password:</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button type=\"submit\">Se connecter</button>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
