/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-13 02:04:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agentajouter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"../JS/1351.js\"></script>\r\n");
      out.write("<script src=\"../JS/jquery-3.4.1.js\"></script>\r\n");
      out.write("<title>Ajouter un agent</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../Style/MonStyle.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"../Images/icon4.ico\" />\r\n");
      out.write("<style>\r\n");
      out.write(".my-form {\r\n");
      out.write("\twidth: 650px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.log {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: #222;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- navbar -->\r\n");
      out.write("\t<div id=\"nav-placeholder\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"contenu\">\r\n");
      out.write("\t\t<form class=\"my-form\" action=\"ajoutagent\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form header -->\r\n");
      out.write("\t\t\t<div class=\"form-header\">\r\n");
      out.write("\t\t\t\t<h1>Nouveau Agent</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form body -->\r\n");
      out.write("\t\t\t<div class=\"form-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- nom et prenom -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"nom\" class=\"label-title\">Nom *</label> <input type=\"text\" id=\"nom\" class=\"form-input\" name=\"nom\" placeholder=\"saisir votre nom\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"prenom\" class=\"label-title\">Prenom *</label> <input type=\"text\" id=\"prenom\" class=\"form-input\" name=\"prenom\" placeholder=\"saisir votre prenom \" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- tel et sex -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"numpriv\" class=\"label-title\">N° téléphone *</label> <input type=\"text\" id=\"numpriv\" class=\"form-input\" name=\"numtel\" placeholder=\"xx xxx xxx\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\tpattern=\"[0-9]{2} [0-9]{3} [0-9]{3}\"\r\n");
      out.write("\t\t\t\t\t\t/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"adress\" class=\"label-title\">Région *</label> <select name=\"region\" id=\"adress\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir une région --</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ariana\">Ariana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Beja\">Béja</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Ben Arous\">Ben Arous</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Bizerte\">Bizerte</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Gabes\">Gabés</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Gafsa\">Gafsa</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Jendouba\">Jendouba</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kairouan\">Kairouan</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"El Kasserine\">El Kasserine</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Kebili\">Kébili</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Le Kef\">Le Kef</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mahdia\">Mahdia</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"La Manouba\">La Manouba</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mednine\">Médnine</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Monastir\">Monastir</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Nabeul\">Nabeul</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sfax\">Sfax</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sidi Bouzid\">Sidi Bouzid</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Siliana\">Siliana</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Sousse\">Sousse</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tataouine\">Tataouine</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tozeur\">Tozeur</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Tunis\">Tunis</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Zaghouan\">Zaghouan</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Sexe et Photo -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"label-title\">Sexe *</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"sexe\" id=\"sexe\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir le sexe --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Homme\">Homme</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Femme\">Femme</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"adress\" class=\"label-title\">Photo *</label> <br> <input type=\"file\" name=\"file2\" accept=\"image/*\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form-footer -->\r\n");
      out.write("\t\t\t<div class=\"form-footer\">\r\n");
      out.write("\t\t\t\t<span>* obligatoire</span> <a href=\"home\">Retour</a>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn\">Ajouter</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- javascript -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t  $(\"#nav-placeholder\").load(\"../navbar.html\");\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
