/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-13 02:44:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ajoutagent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"../1351.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../Styles/MonStyle.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".my-form {\r\n");
      out.write("\twidth: 650px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.log {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: #222;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"aff(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${authenticated}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\" >\r\n");
      out.write("\t<header class=\"header black-bg\">\r\n");
      out.write("\t\t<i class=\"fas fa-bars toggle\" onclick=\"toggle()\" id=\"b\"></i>\r\n");
      out.write("\t\t<h3 style=\"color: white; text-align: center;\">AGENCE IMMOBILIER\r\n");
      out.write("\t\t\tLUXE</h3>\r\n");
      out.write("\t\t<a class=\"log\" href=\"/backoffice/login\" style=\"display: none;\"id=\"con\">Login</a>\r\n");
      out.write("\t\t<a class=\"log\" href=\"/backoffice/logout\"style=\"display: none;\" id=\"discon\">Logout</a>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div id=\"div1\" data-special-value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScopeauthenticated}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></div>\r\n");
      out.write("\t<div id=\"contenu\">\r\n");
      out.write("\t\t<form class=\"my-form\" action=\"ajoutagent\" method=\"post\"\r\n");
      out.write("\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form header -->\r\n");
      out.write("\t\t\t<div class=\"form-header\">\r\n");
      out.write("\t\t\t\t<h1>Nouveau Agent</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form body -->\r\n");
      out.write("\t\t\t<div class=\"form-body\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- nom et prenom -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"nom\" class=\"label-title\">Nom *</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" id=\"nom\" class=\"form-input\" name=\"nom\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"saisir votre nom\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"prenom\" class=\"label-title\">Prenom *</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" id=\"prenom\" class=\"form-input\" name=\"prenom\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"saisir votre prenom \" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- tel et sex -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"numpriv\" class=\"label-title\">N° téléphone *</label> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"text\" id=\"numpriv\" class=\"form-input\" name=\"numtel\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"xx xxx xxx\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\tpattern=\"[0-9]{2} [0-9]{3} [0-9]{3}\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"label-title\">Sexe *</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"homme\"><input type=\"radio\" name=\"sexe\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"homme\" id=\"male\" required=\"required\" checked=\"checked\">\r\n");
      out.write("\t\t\t\t\t\t\t\tHomme</label> <label for=\"femme\"><input type=\"radio\" name=\"sexe\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"femme\" id=\"female\" required=\"required\"> Femme</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Adress -->\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"adress\" class=\"label-title\">Adress *</label>\r\n");
      out.write("\t\t\t\t\t<textarea class=\"form-input\" name=\"adress\" rows=\"4\" cols=\"50\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: auto\" required=\"required\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t<label for=\"adress\" class=\"label-title\">Photo *</label> <br> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"file\" name=\"file2\" multiple=\"multiple\" accept=\"image/*\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form-footer -->\r\n");
      out.write("\t\t\t<div class=\"form-footer\">\r\n");
      out.write("\t\t\t\t<span>* obligatoire</span> <a href=\"../home\">Retour</a>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn\">Ajouter</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"nav\" id=\"nav\" style=\"display: block\">\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-house-user fi\"></i> <span>Propriétaire</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-user-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-user-headset fi\"></i> <span>Agent</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\"\r\n");
      out.write("\t\t\t\t\tonclick=\"window.location.href = '/backoffice/prive/ajouteragent';\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-user-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\"\r\n");
      out.write("\t\t\t\t\tonclick=\"window.location.href = '/backoffice/prive/chercheagent.html';\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-house-return fi\"></i> <span>Visite</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-calendar-plus fi\"></i> <span>Programmer</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-house fi\"></i> <span>Bien</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-user fi\"></i> <span>client</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-user-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-file fi\"></i> <span>contrat</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-file-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-file-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"nav-item\">\r\n");
      out.write("\t\t\t<div class=\"main-item\">\r\n");
      out.write("\t\t\t\t<i class=\"fad fa-comments-alt fi\"></i> <span>Message</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"sub-items\">\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-file-plus fi\"></i> <span>Ajouter</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"sub-item\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fad fa-file-search fi\"></i> <span>Chercher</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction toggle() {\r\n");
      out.write("\t\t\tdocument.getElementById(\"nav\").classList.toggle('active');\r\n");
      out.write("\t\t\tdocument.getElementById(\"contenu\").classList.toggle('active');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction aff(coon){\r\n");
      out.write("\t\t\t  if (coon === undefined) {\r\n");
      out.write("\t\t\t\t    coon = 0;\r\n");
      out.write("\t\t\t  }  \r\n");
      out.write("\t\t\t  if (coon==1){\r\n");
      out.write("\t\t\t\t  document.getElementById(\"discon\").style.display = \"block\";\r\n");
      out.write("\t\t\t  } else {\r\n");
      out.write("\t\t\t\t  document.getElementById(\"con\").style.display = \"block\";\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
