/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-06-26 12:04:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bienajouter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1585607753550L));
    _jspx_dependants.put("jar:file:/E:/Formation/Workspace%20java2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/backoffice/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"../JS/1351.js\"></script>\r\n");
      out.write("<script src=\"../JS/ville.js\"></script>\r\n");
      out.write("<script src=\"../JS/jquery-3.4.1.js\"></script>\r\n");
      out.write("<title>Ajouter un bien</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../Style/MonStyle.css\">\r\n");
      out.write("<link rel=\"icon\" href=\"../Images/icon4.ico\" />\r\n");
      out.write("<style>\r\n");
      out.write(".my-form {\r\n");
      out.write("\twidth: 650px;\r\n");
      out.write("\tmargin-bottom: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.log {\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tbackground: #222;\r\n");
      out.write("\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\ttop: 10px;\r\n");
      out.write("\tright: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#erreur {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin-bottom: 30px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tcolor: red\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- navbar -->\r\n");
      out.write("\t<div id=\"nav-placeholder\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- contenu -->\r\n");
      out.write("\t<div id=\"contenu\">\r\n");
      out.write("\t\t<form class=\"my-form\" action=\"ajouterbien\" method=\"post\" enctype=\"multipart/form-data\" autocomplete=\"off\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form header -->\r\n");
      out.write("\t\t\t<div class=\"form-header\">\r\n");
      out.write("\t\t\t\t<h1>Nouveau Bien</h1>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"delegationn\" value=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- form body -->\r\n");
      out.write("\t\t\t<div class=\"form-body\">\r\n");
      out.write("\t\t\t\t<span id=\"erreur\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${erreur}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t\t\t\t<!-- infos générales -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\" style=\"width: 74%\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"descriptif\" class=\"label-title\">Descriptif *</label> <input type=\"text\" id=\"descriptif\" name=\"descriptif\" class=\"form-input\" placeholder=\"Court descriptif\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\" style=\"width: 24%\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"idprop\" class=\"label-title\">ID Propriétaire *</label><select id=\"idprop\" name=\"idprop\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir --</option>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Adresse : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\" style=\"margin-bottom: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"width: 74%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"rue\" class=\"label-title\">Rue *</label> <input type=\"text\" id=\"rue\" name=\"rue\" class=\"form-input\" placeholder=\"Rue\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\" style=\"width: 24%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"numero\" class=\"label-title\">N° *</label> <input type=\"number\" id=\"numero\" name=\"numero\" class=\"form-input\" placeholder=\"N°\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"codepostal\" class=\"label-title\">Code Postal *</label> <input type=\"number\" id=\"codepostal\" name=\"codepostal\" class=\"form-input\" placeholder=\"Code Postal\" pattern=\"[0-9]{4}\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"region\" class=\"label-title\">Région *</label> <select name=\"region\" id=\"region\" class=\"form-input\" required=\"required\" onchange=\"gov(0)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir une région --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Ariana\">Ariana</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Beja\">Béja</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Ben Arous\">Ben Arous</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Bizerte\">Bizerte</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Gabes\">Gabés</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Gafsa\">Gafsa</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Jendouba\">Jendouba</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Kairouan\">Kairouan</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"El Kasserine\">El Kasserine</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Kebili\">Kébili</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Le Kef\">Le Kef</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Mahdia\">Mahdia</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"La Manouba\">La Manouba</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Medenine\">Médenine</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Monastir\">Monastir</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Nabeul\">Nabeul</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Sfax\">Sfax</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Sidi Bouzid\">Sidi Bouzid</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Siliana\">Siliana</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Sousse\">Sousse</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Tataouine\">Tataouine</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Tozeur\">Tozeur</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Tunis\">Tunis</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Zaghouan\">Zaghouan</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"delegation\" class=\"label-title\">Délégation *</label> <select name=\"delegation\" id=\"delegation\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir une délégation --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\" style=\"width:100%\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"superficie\" class=\"label-title\">Superficie (m²) *</label> <input type=\"number\" id=\"superficie\" name=\"superficie\" class=\"form-input\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"soumission\" class=\"label-title\">Date de soumission *</label> <input type=\"date\" id=\"soumission\" name=\"soumission\" class=\"form-input\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"disposition\" class=\"label-title\">Date de disposition *</label> <input type=\"date\" id=\"disposition\" name=\"disposition\" class=\"form-input\" required=\"required\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Type de bien -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"typebien\" class=\"label-title\">Type de bien *</label> <select id=\"typebien\" name=\"typebien\" onchange=\"typeBien(value);\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir un type --</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t1\">Appartement</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t2\">Emplacement</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t6\">Entrepot</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t3\">Maison</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t4\">Studio</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"t5\">Terrain</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Appartement -->\r\n");
      out.write("\t\t\t\t<div id=\"t1\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Appartement : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"margin-bottom: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"anbchambres\" class=\"label-title\">Nb Chambres *</label> <input type=\"number\" id=\"anbchambres\" name=\"anbchambres\" class=\"form-input\" placeholder=\"Nb Chambres\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"anbgarages\" class=\"label-title\">Nb Garages *</label> <input type=\"number\" id=\"anbgarages\" name=\"anbgarages\" class=\"form-input\" placeholder=\"Nb Garages\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\" style=\"margin-bottom: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"aascenseur\" class=\"label-title\">Ascenseur ? *</label> <select id=\"aascenseur\" name=\"aascenseur\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">Oui / Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"oui\">Oui</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"non\">Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"anetage\" class=\"label-title\">N° étage *</label> <input type=\"number\" id=\"anetage\" name=\"anetage\" class=\"form-input\" placeholder=\"N° étage\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"asjardin\" class=\"label-title\">Superficie du jardin (m²) *</label> <input type=\"number\" id=\"asjardin\" name=\"asjardin\" class=\"form-input\" placeholder=\"Superficie du jardin\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"astotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"astotale\" name=\"astotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Maison -->\r\n");
      out.write("\t\t\t\t<div id=\"t3\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Maison : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"width: 32%; padding-right: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mnbchambres\" class=\"label-title\">Nb Chambres *</label> <input type=\"number\" id=\"mnbchambres\" name=\"mnbchambres\" class=\"form-input\" placeholder=\"Nb Chambres\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"width: 32%; padding-right: 10px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mnbgarages\" class=\"label-title\">Nb Garages *</label> <input type=\"number\" id=\"mnbgarages\" name=\"mnbgarages\" class=\"form-input\" placeholder=\"Nb Garages\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"width: 32%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"nbetages\" class=\"label-title\">Nb étages *</label> <input type=\"number\" id=\"nbetages\" name=\"nbetages\" class=\"form-input\" placeholder=\"Nb étages\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"msjardin\" class=\"label-title\">Superficie du jardin (m²) *</label> <input type=\"number\" id=\"msjardin\" name=\"msjardin\" class=\"form-input\" placeholder=\"Superficie du jardin\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mstotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"mstotale\" name=\"mstotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Studio -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"t4\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Studio : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"sstotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"sstotale\" name=\"sstotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\" style=\"margin-bottom: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"sascenseur\" class=\"label-title\">Ascenseur ? *</label> <select id=\"sascenseur\" name=\"sascenseur\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">Oui / Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"oui\">Oui</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"non\">Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"snetage\" class=\"label-title\">N° étage *</label> <input type=\"number\" id=\"snetage\" name=\"snetage\" class=\"form-input\" placeholder=\"N° étage\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Emplacement -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"t2\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Emplacement : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"emstotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"emstotale\" name=\"emstotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"nbpieces\" class=\"label-title\">Nb Piéces *</label> <input type=\"number\" id=\"nbpieces\" name=\"nbpieces\" class=\"form-input\" placeholder=\"Nb Piéces\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Terrain -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"t5\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Terrain : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"tstotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"tstotale\" name=\"tstotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"affectation\" class=\"label-title\">Type d'affectation *</label> <select id=\"affectation\" name=\"affectation\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir un type --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Agricole\">Agricole</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Industriel\">Industriel</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Urban\">Urban</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Entrepot -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"t6\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> Entrepot : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"enstotale\" class=\"label-title\">Superficie totale (m²) *</label> <input type=\"number\" id=\"enstotale\" name=\"enstotale\" class=\"form-input\" placeholder=\"Superficie totale\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"equip\" class=\"label-title\">Equipé de :</label><br> <input type=\"checkbox\" id=\"equip1\" name=\"equip1\" value=\"Bloc saniatire\"> <label for=\"equip1\">Bloc saniatire</label><br> <input type=\"checkbox\" id=\"equip2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"equip2\" value=\"Bloc administrative\"\r\n");
      out.write("\t\t\t\t\t\t\t> <label for=\"equip2\"> Bloc administrative</label><br> <input type=\"checkbox\" id=\"equip3\" name=\"equip3\" value=\"Loge gardien\"> <label for=\"equip3\">Loge gardien</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Mode d'offre -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"modeoffre\" class=\"label-title\">Mode d'offre *</label><select id=\"modeoffre\" name=\"modeoffre\" onchange=\"modeOffre(value);\" class=\"form-input\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir un mode --</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"m1\">A Vendre</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"m2\">A Louer</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- A Vendre -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"m1\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> A Vendre : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"prixdemande\" class=\"label-title\">Prix Demandé (DT) *</label> <input type=\"number\" id=\"prixdemande\" name=\"prixdemande\" class=\"form-input\" placeholder=\"Prix Demandé\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"etat\" class=\"label-title\">Etat *</label> <select id=\"etat\" name=\"etat\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option disabled selected value=\"\">-- Choisir un état --</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Impeccable\">Impeccable</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"Correct\">Correct</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"A Restaurer\">A Restaurer</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- A Louer -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\" id=\"m2\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<legend> A Louer : </legend>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"caution\" class=\"label-title\">Montant de la caution (DT) *</label> <input type=\"number\" id=\"caution\" name=\"caution\" class=\"form-input\" placeholder=\"Montant de la caution\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"loyer\" class=\"label-title\">Loyer Mensuel (DT) *</label> <input type=\"number\" id=\"loyer\" name=\"loyer\" class=\"form-input\" placeholder=\"Loyer Mensuel\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"charges\" class=\"label-title\">Charges Mensuels (DT) *</label> <input type=\"number\" id=\"charges\" name=\"charges\" class=\"form-input\" placeholder=\"Charges Mensuels\" value=\"0\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group right\" style=\"margin-bottom: 0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group left\" style=\"width: 55%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"typebail\" class=\"label-title\">Type de Bail *</label> <select id=\"typebail\" name=\"typebail\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">Choisir</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Mixte\">Mixte</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Commercial\">Commercial</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Professionnel\">Professionnel</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group right\" style=\"width: 43%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"meuble\" class=\"label-title\">Meublé ? *</label> <select id=\"meuble\" name=\"meuble\" class=\"form-input\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option disabled selected value=\"\">Oui / Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Oui\">Oui</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"Non\">Non</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Autres -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"nom\" class=\"label-title\">Caractéristiques :</label><br> <input type=\"checkbox\" id=\"carac1\" name=\"carac1\" value=\"Chauffage central\"> <label for=\"carac1\">Chauffage central</label><br> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"carac2\" name=\"carac2\" value=\"Systeme de securite\"\r\n");
      out.write("\t\t\t\t\t\t> <label for=\"carac2\">Système de sécurité</label><br> <input type=\"checkbox\" id=\"carac3\" name=\"carac3\" value=\"Piscine\"> <label for=\"carac3\">Piscine</label><br> <input type=\"checkbox\" id=\"carac4\" name=\"carac4\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Climatisation\"\r\n");
      out.write("\t\t\t\t\t\t> <label for=\"carac4\">Climatisation</label><br> <input type=\"checkbox\" id=\"carac5\" name=\"carac5\" value=\"Vue sur mer\"> <label for=\"carac5\">Vue sur mer</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group right\">\r\n");
      out.write("\t\t\t\t\t\t<label style=\"visibility: hidden\">vide</label><br> <input type=\"checkbox\" id=\"carac6\" name=\"carac6\" value=\"Suite parentale\"> <label for=\"carac6\">Suite parentale</label><br> <input type=\"checkbox\" id=\"carac7\" name=\"carac7\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Sous-sol\"\r\n");
      out.write("\t\t\t\t\t\t> <label for=\"carac7\">Sous-sol</label><br> <input type=\"checkbox\" id=\"carac8\" name=\"carac8\" value=\"Cuisine equipe\"> <label for=\"carac8\">Cuisine équipé</label><br> <input type=\"checkbox\" id=\"carac9\" name=\"carac9\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Maison intelligente\"\r\n");
      out.write("\t\t\t\t\t\t> <label for=\"carac9\">Maison intelligente</label><br> <input type=\"checkbox\" id=\"carac10\" name=\"carac10\" value=\"Terrasse\"> <label for=\"carac10\">Terrasse</label><br> <label style=\"visibility: hidden\">vide</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Photos -->\r\n");
      out.write("\t\t\t\t<div class=\"horizontal-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group left\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"photos\" class=\"label-title\">Photo *</label> <br> <input type=\"file\" id=\"photos\" name=\"photos\" accept=\"image/*\" multiple />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- form-footer -->\r\n");
      out.write("\t\t\t<div class=\"form-footer\">\r\n");
      out.write("\t\t\t\t<span>* obligatoire</span> <a href=\"../home\">Retour</a>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn\">Ajouter</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- javascript -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\t$(\"#nav-placeholder\").load(\"../navbar.html\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdocument.getElementById('soumission').valueAsDate = new Date();\r\n");
      out.write("\t\tfunction typeBien(value) {\r\n");
      out.write("\t\t\tfor (i = 1; i < 7; i++) {\r\n");
      out.write("\t\t\t\tif (\"t\" + i != value) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"t\" + i).style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t$(\"#t\" + i + \" input\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).removeAttr('required');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\"#t\" + i + \" select\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).removeAttr('required');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(value).style.display = \"block\";\r\n");
      out.write("\t\t\t$(\"#\" + value + \" input\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).attr('required', '');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#\" + value + \" select\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).attr('required', '');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tdocument.getElementById('equip1').removeAttribute('required');\r\n");
      out.write("\t\t\tdocument.getElementById('equip2').removeAttribute('required');\r\n");
      out.write("\t\t\tdocument.getElementById('equip3').removeAttribute('required');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction modeOffre(value) {\r\n");
      out.write("\t\t\tfor (i = 1; i < 3; i++) {\r\n");
      out.write("\t\t\t\tif (\"m\" + i != value) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"m\" + i).style.display = \"none\";\r\n");
      out.write("\t\t\t\t\t$(\"#m\" + i + \" input\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).removeAttr('required');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\"#m\" + i + \" select\").each(function() {\r\n");
      out.write("\t\t\t\t\t\t$(this).removeAttr('required');\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(value).style.display = \"block\";\r\n");
      out.write("\t\t\t$(\"#\" + value + \" input\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).attr('required', '');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#\" + value + \" select\").each(function() {\r\n");
      out.write("\t\t\t\t$(this).attr('required', '');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/bienajouter.jsp(61,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("id");
      // /WEB-INF/bienajouter.jsp(61,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/bienajouter.jsp(61,7) '${ids}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ids}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
